name: publish (latest)

on:
  push:
    tags:
      - google-analytics-v*
      - test-v*

jobs:
  publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # == region variables
      - run: echo "::set-output name=result::${GITHUB_REF/refs\/tags\//}"
        id: targetTag
      - run: echo "targetTag:${{steps.targetTag.outputs.result}}"
      # == endregion
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@classi'
      - run: yarn
      - name: google-analytics
        if: ${{ startsWith(steps.targetTag.outputs.result, 'google-analytics-v') }}
        run: ./tools/scripts/publish-latest.sh "google-analytics"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: test
        if: ${{ startsWith(steps.targetTag.outputs.result, 'test-v') }}
        run: echo 'test'
