name: publish (latest)

on:
  push:
    tags:
      - google-analytics-v*
      - test-v*

jobs:
  publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: prepare vars
        id: vars
        run: | 
          echo "::set-output name=validBranch::$(git branch --contains HEAD --format "%(refname:lstrip=2)" | grep -e 'main' -e 'action-on-release-tag')\n"
          echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}\n"
      - run: echo "valid branch = ${{steps.vars.outputs.validBranch}}"
      - run: echo "target tag = ${{steps.vars.outputs.tag}}"
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - name: google-analytics
        if: ${{ startsWith(steps.vars.outputs.tag, 'google-analytics-v') }}
        run: yarn build google-analytics --prod
      - name: test
        if: ${{ startsWith(steps.vars.outputs.tag, 'test-v') }}
        run: echo 'test'
