name: publish (latest)

on:
  push:
    tags:
      - google-analytics-v*
      - test-v*

jobs:
  publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Reattach to branch
        run: git checkout -b "publishing"
      - run: echo $(git branch --contains ${GITHUB_SHA} --format "%(refname:lstrip=2)")
      - run: echo "::set-output name=result::$(git branch --contains ${GITHUB_SHA} --format "%(refname:lstrip=2)" | egrep "action-on-release-tag")"
        id: validBranch
      - run: echo "::set-output name=result::${GITHUB_REF/refs\/tags\//}"
        id: targetTag
        
      - run: echo "valid branch = [${{steps.validBranch.outputs.result}}]"
      - run: echo "target tag = [${{steps.targetTag.outputs.result}}]"
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - name: google-analytics
        if: ${{ startsWith(steps.targetTag.outputs.result, 'google-analytics-v') }}
        run: yarn build google-analytics --prod
      - name: test
        if: ${{ startsWith(steps.targetTag.outputs.result, 'test-v') }}
        run: echo 'test'
