name: publish (next)

on:
  push:
    branches:
      # - main
      - publish-next-on-master-commits

jobs:
  publish-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch origin master
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x 
      - run: yarn
      - run: echo "::set-output name=result::$(yarn affected:libs --plain --base=origin/master~1)"
        id: affected_libs
      - run: echo ${steps.affected_libs.outputs.result}

