name: publish (next)

on:
  push:
    branches:
      - main

jobs:
  publish-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x 
      - run: yarn
      - run: yarn build:libs
      - run: ./tools/scripts/publish-next.sh ${GITHUB_SHA}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      

